version: '2'
services:
  koa:
    build: .
    ports:
     - "3000"
  nginx:
    build: ./nginx
    volumes:
      - /var/log/nginx:/var/log/nginx:rw
    ports:
      - "80:80"
    links:
      - koa
  rtmp:
    image: jasonrivers/nginx-rtmp
    volumes:
      - /var/log/rtmp:/opt/nginx/logs:rw
    ports:
      - "8080:8080"
      - "1935:1935"
